<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.cloud</groupId>
        <artifactId>framework-starter</artifactId>
        <version>0.2.0-SNAPSHOT</version>
    </parent>

    <artifactId>framework-starter-id-cosid</artifactId>
    <packaging>jar</packaging>

    <name>framework-starter-id-cosid</name>

    <dependencies>
        <dependency>
            <groupId>com.cloud</groupId>
            <artifactId>framework-id</artifactId>
        </dependency>
        <dependency>
            <groupId>me.ahoo.cosid</groupId>
            <artifactId>cosid-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
